apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: busy
spec:
  containers:
  - image: busybox
    volumeMounts:
    - mountPath: /busy
      name: test
    name: busy
    command:
    - sleep
    - "360"
  - image: busybox
    volumeMounts:
      - mountPath: /box
        name: test
    name: box
    command:
    - sleep
    - "360"
  volumes:
  - name: test
    emptyDir: {}
